#   Type The Delay Time Which The Block Will Regen After Broken By A Player !
#   Default Time Is 6
delay: 6
#   Type The World Name Where The Plugin Will Work !
#   Default Level Name Is dungeon
levelname: dungeon

#   Now Here You Can Customize The Block If They Can Regen Or Not
coal_ore: true
iron_ore: true
gold_ore: true
diamond_ore: true
emerald_ore: true
quartz_ore: true
lapis_ore: true
carrot_block: true
potato_block: true
pumkin: true
cactus: true
melon_block: true